name: Test Env

on:
  workflow_dispatch:
    inputs:
      param:
        description: 'parameter'
        required: false
        default: ''

jobs:
  build:
    runs-on: Ubuntu-22.04
    steps:

    - name: Create file
      run:  |
        echo  'test action' >> 1.txt
      
    - name: Deploy imagebuilder to server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avzr"
        SOURCE: 1.txt
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_PORT: ${{ secrets.SERVER_PORT }}
        REMOTE_USER: root
        TARGET: "/home/upload/"

